Fix bugs in mk_repo and change build.info location

diff --git a/binaries/mk_repo b/binaries/mk_repo
--- a/binaries/mk_repo
+++ b/binaries/mk_repo
@@ -27,6 +27,14 @@ usage() {
 	exit 1
 }
 
+check_code() {
+  if [ $1 -ne 0 ]; then
+    echo -e "Error: Code: $1"
+    echo -e "Output:\n$2"
+    exit $1
+  fi
+}
+
 check_args() {
 	if [ -z "${arg1}" ]; then
 		usage
@@ -42,28 +50,37 @@ check_valid_path() {
 
 source_package() {
 	local packagename="${1}"
-	. $packagename/control
+	. $tmp_folder/$packagename/control
+	check_code $? "Error during source control file (. $tmp_folder/$packagename/control)"
 	NO_ARCH=false
 	NO_DIST=false
 	NO_DISTVERS=false
 }
 
+create_tmp() {
+	tmp_folder=$(mktemp -d)
+}
+
 untar_package() {
-	local filename="${1}"
-	tar xf "${filename}"
+	local fullpath="${1}"
+	local filename="${2}"
+	tar xf "$fullpath"/"${filename}" -C $tmp_folder
+	check_code $? "Error during untar package (tar xf $tmp_folder/${filename} -C $tmp_folder)"
 }
 
 remove_tar() {
 	local packagename="${1}"
-	rm -Rf "${packagename}"
+	rm -Rf $tmp_folder/"${packagename}"*
+	check_code $? "Error during remove package (rm -Rf $tmp_folder/${packagename}*)"
 }
 
 add_to_packages_list() {
-	local packagename="${1}"
-	local MD5=$(md5sum $packagename.tar | awk '{ print $1 }')
-	local PKG_ARCH="${2}"
-	local PKG_DIST="${3}"
-	local PKG_DISTVERS="${4}"
+	local fullpath="${1}"
+	local packagename="${2}"
+	local MD5=$(md5sum $fullpath/$packagename.tar | awk '{ print $1 }')
+	local PKG_ARCH="${3}"
+	local PKG_DIST="${4}"
+	local PKG_DISTVERS="${5}"
 	if [ $NO_ARCH == true ]; then
 		PKG_ARCH="noarch"
 	fi
@@ -82,35 +99,48 @@ list_packages() {
 	local ARCH="${1}"
 	local DIST="${2}"
 	local DIST_VERS="${3}"
-	for package in "${REPO_PATH}"/"${ARCH}"/"${DIST}"/"${DIST_VERS}"/*; do
-		filename=$(echo $package | sed "s,${REPO_PATH}/${ARCH}/${DIST}/${DIST_VERS}/,,")
+	local FULL_PATH="${REPO_PATH}"/"${ARCH}"/"${DIST}"/"${DIST_VERS}"
+	for package in "${FULL_PATH}"/*; do
+		filename=$(echo $package | sed "s,${FULL_PATH}/,,")
 		if [ $(echo $filename | awk -F . '{print $NF}') == "tar" ]; then
 			packagename=$(basename $package .tar)
-			untar_package "${filename}"
+			echo "       | $packagename"
+			untar_package "${FULL_PATH}" "${filename}"
 			source_package "${packagename}"
-			add_to_packages_list "${packagename}" "${ARCH}" "${DIST}" "${DIST_VERS}"
-			echo "         | "${packagename}""
-			remove_tar "${packagename}"
+			add_to_packages_list "${FULL_PATH}" "${packagename}" "${ARCH}" "${DIST}" "${DIST_VERS}"
+			remove_tar "${FULL_PATH}""${packagename}"
+			cd $REPO_PATH
 		fi
 	done
 }
 
 list_folder() {
-	REPO_PATH=$(pwd "${arg1}")
-	echo " :: Repo path: "${REPO_PATH}""
+	REPO_PATH="${arg1}"
+	if [ -z "$(ls -l $REPO_PATH | grep "^d")" ]; then
+		echo "    + Error: Repo is empty"
+		exit 1
+	fi
+	if [ "$REPO_PATH" == "." ]; then
+		REPO_PATH=$(pwd .)
+	fi
 	if [ $(echo ${REPO_PATH} | sed 's/^.*\(..\)$/\1/') == "/" ]; then
 		REPO_PATH=$(echo "${REPO_PATH}"*/ | sed '$s/.$///')
 	fi
-		archs=$(ls -d1 "${REPO_PATH}"/*/ | sed "s|^${REPO_PATH}/||")
+	echo " :: Repo path: "${REPO_PATH}""
+	archs=$(ls -d1 "${REPO_PATH}"/*/ | sed "s|^${REPO_PATH}/||")
 	for arch in ${archs}; do
+		check_code $? "Error during ls ${REPO_PATH}"
 		arch=$(echo "${arch}" | sed '$s/.$//')
 		echo " :: Arch: "${arch}""
 		distribs=$(ls -d1 "${REPO_PATH}"/"${arch}"/*/ | sed "s|^${REPO_PATH}/${arch}/||")
+		check_code $? "Error during ls ${REPO_PATH}/${arch}"
 		for distrib in ${distribs}; do
+			check_code $? "Error during ls ${REPO_PATH}/${arch}/${distrib}"
 			distrib=$(echo "${distrib}" | sed '$s/.$//')
 			echo "    + Distrib: "${distrib}""
 			versions=$(ls -d1 "${REPO_PATH}"/"${arch}"/"${distrib}"/*/ | sed "s|^${REPO_PATH}/${arch}/${distrib}/||")
 			for version in ${versions}; do
+				check_code $? "Error during ls ${REPO_PATH}/${archs}/${distribs}/${versions}"
 				version=$(echo "${version}" | sed '$s/.$//')
 				echo "       + Version: "${version}""
 				cd "${REPO_PATH}"/"${arch}"/"${distrib}"/"${version}"
@@ -124,8 +154,9 @@ list_folder() {
 # Run #
 #######
 arg1="${1}"
-
 check_args
 check_valid_path
 rm -Rf $arg1/Packages.list
+create_tmp
 list_folder
+rm -Rf $tmp_folder
