Update pkgmgr output style and fix some minor bugs

diff --git a/sources/pkgmgr/bin/pkgmgr b/sources/pkgmgr/bin/pkgmgr
--- a/sources/pkgmgr/bin/pkgmgr
+++ b/sources/pkgmgr/bin/pkgmgr
@@ -76,8 +76,13 @@ function show_help(){
 
 function ask_confirmation() {
 	if [ "$OPT" != "--force-yes" ]; then
-		read -p "Are you sure? [y|N] " -n 1
-		if [[ ! $REPLY =~ ^[Yy]$ ]]; then echo && exit 1; fi
+		read -p "Do you want to continue [y/N]? " -n 1
+		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+			echo 
+			echo "Abort." && exit 1
+		else
+			echo
+		fi
 	fi
 }
 
@@ -103,8 +108,16 @@ function pkg_list() {
 
 function print_deps() {
 	for dep in $1; do
-		echo "  - $dep"
+		echo "      - $dep"
 	done
+}
+
+function check_args() {
+	if [[ $# -le 1 && "$OPT" != "--force-yes" ]]; then
+		show_help
+	elif [[ $# -le 2 && "$OPT" == "--force-yes" ]]; then
+		show_help
+	fi
 }
 
 ###############
@@ -115,27 +128,33 @@ OPT=$2
 
 if [[ "x$ACTION" =~ ^(xinstall|xreinstall|xinstall-local|xreinstall-local|xupgrade|xremove|xlist|xclean|xupdate)$ ]]; then
 	if [ "x$ACTION" = "xinstall" ]; then
+		check_args $@
 		update_db && pkg_list_deps "$@"
-		echo -e "Following dependencies will be installed: " && print_deps "$pkg_list_deps"
+		echo " :: Resolve dependencies"
+		echo "    + Following dependencies will be installed" && print_deps "$pkg_list_deps"
 		ask_confirmation
 		install_package $pkg_list_deps && exit $?; fi
 	if [ "x$ACTION" = "xreinstall" ]; then 
+		check_args $@
 		update_db && pkg_list "$@"
 		install_package $pkg_list "_force" && exit $?; fi
 	if [ "x$ACTION" = "xinstall-local" ]; then 
-		pkg_list_deps "$@"
-		echo "Following dependencies will be installed: " && print_deps "$pkg_list_deps"
-		ask_confirmation
-		install_local_package $pkg_list_deps && exit $?; fi
+		check_args $@
+		pkg_list "$@"
+		install_local_package $pkg_list && exit $?; fi
 	if [ "x$ACTION" = "xreinstall-local" ]; then
+		check_args $@
 		pkg_list "$@"
 		install_local_package $pkg_list "_force" && exit $?; fi
 	if [ "x$ACTION" = "xupgrade" ]; then
+		check_args $@
 		update_db && pkg_list "$@"
 		upgrade_package $pkg_list && exit $?; fi
-	if [ "x$ACTION" = "xremove"  ]; then
+	if [ "x$ACTION" = "xremove" ]; then
+		check_args $@
 		pkg_list_deps "$@"
-        echo "Following dependencies will be removed: " && print_deps "$pkg_list_deps"
+		echo " :: Resolve dependencies"
+        echo "    + Following dependencies will be removed" && print_deps "$pkg_list_deps"
         ask_confirmation
 		remove_package $pkg_list_deps && exit $?; fi
 	if [ "x$ACTION" = "xupdate" ]; then 
