Fix bug #70

diff --git a/sources/pkgmgr/bin/pkgmgr b/sources/pkgmgr/bin/pkgmgr
--- a/sources/pkgmgr/bin/pkgmgr
+++ b/sources/pkgmgr/bin/pkgmgr
@@ -188,7 +188,7 @@ if [[ "x$ACTION" =~ ^(xinstall|xreinstall|xinstall-local|xreinstall-local|xupgra
 	if [ "x$ACTION" = "xinstall" ]; then
 		check_args $@
 		update_db
-		trap 'error ${LINENO} "Package dependencie failure, loot at: ($LOG_FILE)"' ERR
+		trap 'error ${LINENO} "Package dependencie failure, look at: ($LOG_FILE)"' ERR
 		pkg_list_install_deps "$@"
 		echo " :: Resolve dependencies"
 		echo "    + Following dependencies will be installed" && print_deps "$pkg_list_deps"
@@ -209,7 +209,7 @@ if [[ "x$ACTION" =~ ^(xinstall|xreinstall|xinstall-local|xreinstall-local|xupgra
 	if [ "x$ACTION" = "xupgrade" ]; then
 		check_args $@
 		update_db
-		trap 'error ${LINENO} "Package dependencie failure, loot at: ($LOG_FILE)"' ERR
+		trap 'error ${LINENO} "Package dependencie failure, look at: ($LOG_FILE)"' ERR
 		pkg_list_install_deps "$@"
 		echo " :: Resolve dependencies"
 		echo "    + Following dependencies will be installed or upgraded" && print_deps "$pkg_list_deps"
