Clean pkgmgr and fix bugs

diff --git a/sources/pkgmgr/lib/pkgmgr/actions b/sources/pkgmgr/lib/pkgmgr/actions
--- a/sources/pkgmgr/lib/pkgmgr/actions
+++ b/sources/pkgmgr/lib/pkgmgr/actions
@@ -34,33 +34,46 @@ function download_package(){
     #wget -O $PACKAGES_PATH/$PNAME.tgz -a $LOG_PATH --progress=dot "$FINAL_URL/$PNAME.tgz" 2>&1 | grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}'
     wget --progress=dot "$FINAL_URL/$PNAME.tgz" 2>&1 | grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}'
     echo -ne "\b\b\b\b"
-    echo "     + DONE"
+    echo "         + Done"
     check_code $? "Failure during download package"
 }
 
 function install_package(){
+	update_db
     PNAME=$1
     DBINFO=$(db_get "$PNAME")
-	
-	update_db
-    download_package "$PNAME"
-
-    L_STATUS=$(db_parse "status" "$DBINFO")
+	L_STATUS=$(db_parse "status" "$DBINFO")
     if [ "$L_STATUS" == "installed" ]; then
         echo " :: Reinstall package $PNAME"
     else
         echo " :: Install package $PNAME"
     fi
 
-    R_INFO=$(echo `cat $REMOTE_DB_PATH | grep $PNAME | tail -n1`)
-    R_MD5=$(db_parse "md5" "$R_INFO")
+	res="False"
+	# LOCAL ARCHIVE
+	if [[ -e $PACKAGES_PATH/$PNAME.tgz ]]; then
+		echo "   + Package archive already in cache"
+		echo "     + Check MD5"
+        R_INFO=$(echo `cat $REMOTE_DB_PATH | grep $PNAME | tail -n1`)
+        R_MD5=$(db_parse "md5" "$R_INFO")
+		PPATH=$(get_ppath "$PNAME")
+        check_code $?
+        L_MD5=$(md5sum $PPATH.tgz | awk '{ print $1 }')
+		if [ "$L_MD5" != "$R_MD5" ]; then echo "       + Invalide MD5Sum" && res=False; fi
+	fi
 
-    PPATH=$(get_ppath "$PNAME")
-    check_code $?
+	# DOWNLOAD PACKAGE
+	if [[ "$res" == "False" ]]; then
+	    download_package "$PNAME"
 
-    L_MD5=$(md5sum $PPATH.tgz | awk '{ print $1 }')
-
-    if [ "$L_MD5" != "$R_MD5" ]; then check_code $? "Md5sum Error!" && exit 0; fi
+	    R_INFO=$(echo `cat $REMOTE_DB_PATH | grep $PNAME | tail -n1`)
+    	R_MD5=$(db_parse "md5" "$R_INFO")
+	    PPATH=$(get_ppath "$PNAME")
+    	check_code $?
+	    L_MD5=$(md5sum $PPATH.tgz | awk '{ print $1 }')
+		 echo "   + Check MD5"
+    	if [ "$L_MD5" != "$R_MD5" ]; then echo "     + Invalide MD5Sum" && exit 1; fi
+	fi
 
 	load_control_tpl
     . $PPATH/control
@@ -77,6 +90,9 @@ function install_package(){
     check_code $? "Post-install function ($PNAME) failure"
     db_set "$PNAME" "$VERSION-$RELEASE" "installed"
 
+	echo "   + Remove package folder"
+	rm -Rf $PPATH
+	check_code $? "Post installation package folder remove failure"
     echo " + Done"
 }
 
